### ISSUE TITLE
The app won't connect to the Internet

### ISSUE THREAD

**Issue by andrewberryca** [emeraldpay/emerald-wallet#1187]
Verson 2.4.1.

Uncaught Exception:
Error: Object has been destroyed
    at click (/Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/@emeraldwallet/electron-app/lib/menus/darwin.js:74:49)
    at MenuItem.click (electron/js2c/browser_init.js:1549:9)
    at Function.executeCommand (electron/js2c/browser_init.js:1810:13) 

Updated to Version 2.6.2. and it doesn't accept the password. >_<

**Comment by andrewberryca** [comment]
Hi Igor,

Thank you so much for getting back to me that quickly.

The new version does go further in terms of sending ETC, but getting stuck on signing your transaction (screenshot attached).
So, basically, when you click "SIGN TRANSACTION" nothing happens, not even an error message.

I guess I need to wait when it'll be released with bug fixes.

Cheers,

Sincerely,
Andrew

![Screen Shot](https://user-images.githubusercontent.com/16826662/172678819-df2f6cef-5ae3-4568-b135-357c6e5ce3c2.jpg)

**Comment by andrewberryca** [comment]
Hi Igor,

Thank you so much for getting back to me that quickly.

The new version does go further in terms of sending ETC, but getting stuck
on signing your transaction (screenshot attached).
So, basically, when you click "SIGN TRANSACTION" nothing happens, not even
an error message.

I guess I need to wait when it'll be released with bug fixes.

Cheers,

Sincerely,
Andrew

[image: Screen Shot 2022-06-08 at 6.28.46 PM.png]
