### ISSUE TITLE
How to restore JSON wallet

### ISSUE THREAD

**Issue by github12101** [emeraldpay/emerald-wallet#1379]
Hello,

I have saved JSON wallet and password to it years ago.
I played a lot with different versions of Emerald Wallet trying to restore it. This is how far I got:
Latest Emerald-Wallet-linux-v2.10.0 fails to import this wallet completely.
Old version Emerald-Wallet-linux-v2.3.0 can import JSON wallet and display my address, however, it will not connect to the network. I checked and this address hold coins.
When I re-open wallet created by 2.3.0 version in latest version, then it asks me to migrate wallet. Then it fails on password entry. When I skip migration, I have my wallet and balance displayed nicely. But when I try to transfer funds out, I have error:
`Error occurred in handler for 'vault-verify-global-key': Error: 200: GlobalKeyRequired`
Global Key is just 12345678, created for the purpose of this migration, so this is weird. And I have password to that JSON file saved, as a KeePass entry, since 2019, it has not changed since. I feel that old version v2.3.0 would use that JSON-based wallet just fine, but it doesn't connect anymore. And new Emerald Wallet does not complete the task.

Any tips how to withdraw funds from this appreciated!

**Comment by github12101** [comment]
This is where latest Emerald Wallet fails. For "Old password" here I just entered password to JSON file. And it fails, error is displayed only to terminal.

```
Error occurred in handler for 'vault-verify-global-key': Error: 200: GlobalKeyRequired
    at buildError (/tmp/.mount_EmeralYMHprs/resources/app.asar/node_modules/@emeraldpay/neon-frame/lib/wrap.js:7:12)
    at resolveStatus (/tmp/.mount_EmeralYMHprs/resources/app.asar/node_modules/@emeraldpay/neon-frame/lib/wrap.js:13:23)
    at /tmp/.mount_EmeralYMHprs/resources/app.asar/node_modules/@emeraldpay/neon-frame/lib/wrap.js:26:24
```

![image](https://github.com/emeraldpay/emerald-wallet/assets/1646393/4f663a57-9eca-4992-8f0d-32de23d0520a)

**Comment by github12101** [comment]
Is there any way I can export a private key from JSON+password? How to decrypt JSON file? My password is correct I am sure, because it has not changed at all since I created it. I have old backups of it since creation of the password, everything is the same. Wallet worked back then, it doesn't now.
